### PR TITLE
Feature/uploading non academic activities report

### PR DESCRIPTION
**Pull request by Dennis-Spiderman**
Changed the view of the function to upload the non academic activities report, added the model to read the student data in the xlsx file, also added the feedback messages about the succesuful and non succesful upload of the xlsx file, centered the divs and made another minor adjustments

### CODE REVIEW

**Review by yuluka — CHANGES_REQUESTED** [review]
Delete js script you don't use.

**Comment by Dennis-Spiderman** [comment]
> Delete js script you don't use.

Ok, done

**Review by yuluka — APPROVED** [review]
Ok

**Review by JacoboOssa — APPROVED** [review]
its ok

**Pull request merged**
