### PR TITLE
Feature/request information update

### PR DESCRIPTION
**Pull request by yuluka**
The view to make requests for information update has been added. 

Also, the __pycache__ has been removed of migrations folder.

### CODE REVIEW

**Comment by JacoboOssa** [comment]
All in order

**Review by JacoboOssa — APPROVED** [review]
its okay, yuluka can merge

**Comment by Dennis-Spiderman** [comment]
Its ok, approved

**Review by Dennis-Spiderman — APPROVED** [review]
OK

**Pull request merged**
